{
  "expected_passed_count": 0,
  "expected_failed_count": 0,
  "expected_errors_count": 1,
  "expected_data_object": {
    "score": 0.0,
    "tests": [
      {
        "max_points": 2,
        "message": "Student code execution failed with an exception: division by zero",
        "name": "test_exception",
        "points": 0.0,
        "test_id": "test_core_exception.py::test_core_exception[student_code]"
      }
    ]
  }
}
